# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

run-name: Deployment of Swagger doc to Heroku App

on:
  push:
    branches: [ "backend-main" ]
  pull_request:
    branches: [ "backend-main" ]

jobs:
  build: ## <-- Start the build process
    runs-on: ubuntu-latest
    
    # set up enviroment variables
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}      
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      
      SQL_DATABASE: ${{ vars.SQL_DATABASE }}
      SQL_HOST: ${{ vars.SQL_HOST }}  
      SQL_PORT: ${{ vars.SQL_PORT }}    
    
    # Change working directory
    defaults:
      run:
        working-directory: ./api

    strategy:
      matrix:
        node-version: [16.x, 18.x] # TODO: In case we want 14.x back try changing alias to node="nodejs"
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # checkout code
    - uses: actions/checkout@v3
    
    # setup node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
        
    # Install dependencies
    - run: npm install
    - run: npm ci
    
    # Build the app
    - run: npm run build --if-present
    
    # TODO: Run tests using Jest
    # - run: npm test
      

  deploy: ## <-- Deployment to Heroku App
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
            heroku_email: ${{ vars.HEROKU_EMAIL }}
            appdir: "api"
